### ISSUE TITLE
Downscaling phase 3 sprites

### ISSUE THREAD

**Issue by mike309game** [KadeDev/trickster#10]
(somewhat related to #3 )
The sprites really doesn't need to be that large since most players have 1080p monitors (runs at 1600x900 windowed) or 1366x768 (1280x720 windowed) for laptops, and even in 1080p the hellclown sprite doesn't fit the whole screen. It's a massive waste of memory and even if someone has some 9999k monitor that is able to display the sprites in their native resolution scaling up things isn't a problem.

**Comment by KadeDev** [comment]
you realize that's not how sprites work right? Tricky himself is not even close to 11kxwhatever, he's more like 1900x2700 for each of his frames, which results in a giant sprite sheet.

We're not looking at downscaling him.

**Comment by mike309game** [comment]
Tricky's whole sheet for all notes & idle is loaded at all times during gameplay, that's something called caching. I've done some looking and the game, and regardless of window size, [is always a 1280x720 surface stretched](https://cdn.discordapp.com/attachments/822172878442332200/849858476162940938/chrome_2021-06-03_00-53-39.png), and [**The sprites lose 66% of their detail in game.**](https://cdn.discordapp.com/attachments/822172878442332200/849860607943507989/2021-06-03_01-01-32.gif)

**Comment by benjaminpants** [comment]
the fact that this was closed is so stupid, so i'm going to make it myself because this is a perfectly reasonable request
