### ISSUE TITLE
Where are the Up Down Left Right Idle animations? They're only body parts.

### ISSUE THREAD

**Issue by GithubPerson2021** [KadeDev/trickster#11]
Do you need a special thing to sprite sheet this?

**Comment by GithubPerson2021** [comment]
I check the xml and it says "Created with Kades Custom Converter" What on earth is that

**Comment by KadeDev** [comment]
for what sprite sheet? what

**Comment by GithubPerson2021** [comment]
how do you make the tricky spritesheet?

**Comment by KadeDev** [comment]
https://twitter.com/KadeDeveloper/status/1400531509543456774

**Comment by GithubPerson2021** [comment]
ok
