### ISSUE TITLE
HTML5 Bug Reports: You cannot access the cpp package while targeting js (for cpp.Lib)

### ISSUE THREAD

**Issue by Stefannag** [KadeDev/trickster#14]
After converting all the songs/music in MP3, I tried to convert the game in HTML using lime, as:

`lime test html5`

It seems that there are some errors at WebmPlayer.hx and ApplicationMain.hx. I've got the following message in CMD:

`C:/HaxeToolkit/haxe/lib/extension-webm/git/webm/WebmPlayer.hx:3: characters 8-15 : You cannot access the cpp package while targeting js (for cpp.Lib)
source/Main.hx:3: characters 8-23 : ... referenced here
export/release/html5/haxe/ApplicationMain.hx:299: characters 48-52 : ... referenced here`

I tried to get some answers by surfing the web, but I couldn't. I saw that for this type of error you would need to make a `build.hxml`, that contains:

`-cp src
-main Main
-cpp bin`

Any ideas regarding this error?

**Comment by KadeDev** [comment]
yes, the cutscenes we are using are noncompatible with html5. in which you would have to use a different way of displaying cutscenes, like how week 7 did on newgrounds.
