### ISSUE TITLE
I can't figure out why nothing will work [Linux]

### ISSUE THREAD

**Issue by BojayB** [KadeDev/trickster#18]
This is kind of a shitty issue, but I'd love to try and give more info if I get a helpful reply. I've followed the instructions by installing Kade engine *and* tricky, and I can't get into the menu. The game launches and the main menu loads, but once I hit enter, the game crashes. I've both git-cloned and downloaded the release on gamebanana and ran with wine but neither versions work. Any ideas?

**Comment by BojayB** [comment]
Well, I've made it into the menu. I redownloaded the game through google drive and ran the executable through wine and it decided to work this time. I'll close if there are no further problems.

**Comment by BojayB** [comment]
Game crashed after the bite down loading screen trying to play story mode. Tried to open again and crashed after the menu. I'm really stumped on what's wrong.

**Comment by BojayB** [comment]
I think the problem is because I only have 6G of memory. Every time I do anything I get a warning about having low memory so my shit just closes it automatically so my pc doesn't crash I think. This sucks

**Comment by oatmealine** [comment]
#10 might help you with this

**Comment by BojayB** [comment]
> #16 might help you with this

How do I get and use it?

**Comment by BojayB** [comment]
> #16 might help you with this

Just tried it, still uses all of my ram and crashes.
