### ISSUE TITLE
Bug Report: Won't compile

### ISSUE THREAD

**Issue by Fefecomitre** [KadeDev/trickster#6]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## Please describe your issue. Provide extensive detail and images if possible.

Alr basically if you run lime test windows, lime test windows -release, lime test windows debug, won't compile and just say source/Main.hx:90: characters 14-29 : Cannot access private field SKIP_STEP_LIMIT
source/Main.hx:90: characters 14-29 : Cannot access private field SKIP_STEP_LIMIT

**Comment by Fefecomitre** [comment]
btw i have installed the extensions and rebuilt them. I use windows x64

**Comment by dark279** [comment]
hiya! i had the same problem. i found a way to fix it. all you gotta do is find wherever the webm library was installed ([haxe folder location]/lib/extension-webm/git/webm/WebmPlayer.hx) and change 
```
static var SKIP_STEP_LIMIT = 0;
``` 
to
```
public static var SKIP_STEP_LIMIT = 0;
```
. that should help!

**Comment by KadeDev** [comment]
or follow the build instructions:
```
haxelib git extension-webm https://github.com/KadeDev/extension-webm
lime rebuild extension-webm windows
```

**Comment by Fefecomitre** [comment]
It is now working! Thanks @dark279 
also kade, i did run the command.

**Comment by Fefecomitre** [comment]
Also quick question does the webm extension only works at the original source? Not on kade engine? I've been trying to compile it but
source/Main.hx:97: characters 3-29 : Type not found : WebmPlayer
source/WebmHandler.hx:12: characters 18-28 : Type not found : WebmPlayer
source/Main.hx:16: lines 16-141 : Defined in this class
source/VideoHandler.hx:4: characters 8-22 : Type not found : motion.Actuate
source/GlobalVideo.hx:50: characters 21-35 : Type not found : GameDimensions
source/GlobalVideo.hx:51: characters 22-36 : Type not found : GameDimensions

**Comment by Fefecomitre** [comment]
hi again, please help, i did run the new command with the kade extension but it keeps coming back, and I did follow that thing that dark said, can someone help me
